= Geschäftsvorschlag
:author: Max Kunzelmann, Manuel Tiedtke, Noah Ströhle

== Geschäftsvorschlag

Das Ziel unseres Projektes ist es den Lernprozess mit einer
Webanwendung zu optimieren. Dazu wird ein __Spaced Repitition System__
entworfen, auf Deutsch oft Karteikartensystem genannt. In diesem kann
der Anwender Fragen-Anwort-Paare entwerfen und bekommt die Fragen in
regelmäßigen Abständen vorgelegt und kann mit der Antwort prüfen, ob
er sich an das Gelernte noch erinnert. Die Abstände zwischen den
Wiederholungen werden so gewählt, dass der Lernerfolg bei minimaler
Wiederholungszahl maximal ist. Nach nur wenigen Wiederholungen wird
das Gelernte ins Langzeitgedächtnis aufgenommen.

<<<

== Pitch

The project aims for optimizing the general learning process for the
user. To achieve that, a __Spaced Repetition System__ is developed.
With this system the user can create question-answer pairs. The
question is shown to the user in regular intervals and he will be able
to check if he remembers the previously written down answer. The
intervals between the reviews are chosen in a way, that memorization
is maximized with a minimal amount of repetitions. Timing is paramount
for this and the app takes care to present the questions at the right
time to the user.

== Time Management

.Roadmap
[grid="rows",width="60%"]
[options="header",cols="^,<"]
|===
| Duration | Description
| 2 weeks  | Pitch, Mockup and Static Prototype
| ? weeks  | Dynamic prototype, basic functionality with database
| ? weeks  | Submission of finished product
|===




